apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsdcn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wsdcn
  template:
    metadata:
      labels:
        app:wsdcn
    spec:
      containers:
      - image: okteto.dev/wsdcn:latest
        name: wsdcn
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "3ba4b9be-08a6-11ed-861d-0242ac120002a"
        - name: Vless_Path
          value: "/vl764"
        - name: Vmess_UUID
          value: "3ba4b9be-08a6-11ed-861d-0242ac120002"
        - name: Vmess_Path
          value: "/vm521"
        - name: Share_Path
          value: "/v2link"
